
platform:ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/baxiaxx/MyTestSpec.git'

target 'MyTest_Example' do
  #pod 'MyTest', :path => '../'
  pod 'MyTest', '~> 1.0'
end